export interface TemplatePreset {
  id: string
  name: string
  description: string
  projectTypes: string[] // matches BasicInfo PROJECT_TYPES; empty means all types
  templateIds: string[]
}

export const PRESETS: TemplatePreset[] = [
  {
    id: 'nextjs-production',
    name: 'Next.js Production',
    description:
      'Complete setup for a production Next.js application with CI/CD, Docker, and code quality tools',
    projectTypes: ['web-app'],
    templateIds: [
      'claude-md',
      'architecture-overview',
      'contributing',
      'security',
      'pr-template',
      'changelog',
      'testing',
      'onboarding',
      'dockerfile',
      'docker-compose',
      'dockerignore',
      'env-example',
      'ci-workflow',
      'cd-workflow',
      'dependabot-config',
      'eslintrc',
      'prettierrc',
      'tsconfig-strict',
      'vscode-settings',
      'vscode-extensions',
    ],
  },
  {
    id: 'api-backend',
    name: 'API Backend',
    description: 'Production API service with OpenAPI spec, Docker, monitoring, and runbook',
    projectTypes: ['api-backend'],
    templateIds: [
      'claude-md',
      'architecture-overview',
      'api-reference',
      'openapi',
      'runbook',
      'contributing',
      'security',
      'pr-template',
      'changelog',
      'testing',
      'dockerfile',
      'docker-compose',
      'dockerignore',
      'env-example',
      'ci-workflow',
      'cd-workflow',
      'health-check-doc',
      'slo-doc',
    ],
  },
  {
    id: 'library-sdk',
    name: 'Library / SDK',
    description: 'Open-source library with strict TypeScript, changelog, and release automation',
    projectTypes: ['library'],
    templateIds: [
      'claude-md',
      'contributing',
      'security',
      'pr-template',
      'changelog',
      'testing',
      'tsconfig-strict',
      'eslintrc',
      'prettierrc',
      'editorconfig',
      'commitlint',
      'dependabot-config',
      'release-workflow',
      'codeowners',
    ],
  },
  {
    id: 'cli-tool',
    name: 'CLI Tool',
    description: 'Command-line tool with Makefile automation and release workflow',
    projectTypes: ['cli-tool'],
    templateIds: [
      'claude-md',
      'contributing',
      'security',
      'pr-template',
      'changelog',
      'testing',
      'makefile',
      'env-example',
      'ci-workflow',
      'release-workflow',
      'commitlint',
      'editorconfig',
      'eslintrc',
    ],
  },
  {
    id: 'monorepo',
    name: 'Monorepo',
    description:
      'Multi-package monorepo with code ownership, commit conventions, and architecture docs',
    projectTypes: ['monorepo'],
    templateIds: [
      'claude-md',
      'architecture-overview',
      'contributing',
      'security',
      'pr-template',
      'changelog',
      'testing',
      'onboarding',
      'codeowners',
      'commitlint',
      'ci-workflow',
      'cd-workflow',
      'dockerfile',
      'env-example',
      'eslintrc',
      'lint-staged',
    ],
  },
  {
    id: 'ai-first',
    name: 'AI-First',
    description: 'Cross-cutting preset for projects that heavily use AI coding agents',
    projectTypes: [], // empty means applies to all project types
    templateIds: [
      'claude-md',
      'agents-md',
      'gemini-md',
      'cursorrules',
      'copilot-instructions',
      'contributing',
      'pr-template',
      'changelog',
    ],
  },
  {
    id: 'minimal',
    name: 'Minimal',
    description: 'Just the essentials — get started fast with 5 key files',
    projectTypes: [], // applies to all types
    templateIds: ['claude-md', 'contributing', 'pr-template', 'changelog', 'env-example'],
  },
]
